sudo: required

language: node_js

node_js: 6.9.5

services:
  - mongodb
  - docker

branches:
  only:
    - staging
    - master

addons:
  apt:
  hosts:
    - localhost
    - dev-controller

before_script:
  - npm install -g grunt-cli
  - docker pull soajsorg/soajs
  - sleep 10

script:
  - grunt coverage
